INSERT INTO products (category_id, name, brand, slug, description, is_active, created_at, updated_at) VALUES
(1, 'MacBook Air 13-inch M2', 'Apple', 'macbook-air-13-m2', 'Thin and light laptop with Apple M2 chip, 8-core CPU, great battery life — ideal for students and professionals.', 1, NOW(), NOW()),
(1, 'ThinkPad X1 Carbon Gen 11', 'Lenovo', 'thinkpad-x1-carbon-gen-11', 'Business ultrabook with carbon-fiber chassis, MIL-STD durability, Intel Core i7 options and enterprise security features.', 1, NOW(), NOW()),
(2, 'iPhone 15', 'Apple', 'iphone-15', 'Flagship smartphone with advanced camera system, A17 chip performance and Ceramic Shield display.', 1, NOW(), NOW()),
(2, 'Galaxy A54 5G', 'Samsung', 'samsung-galaxy-a54-5g', 'Mid-range 5G smartphone with AMOLED screen, solid battery life and excellent value for money.', 1, NOW(), NOW()),
(2, 'Pixel 8a', 'Google', 'google-pixel-8a', 'Clean Android experience, excellent computational photography and guaranteed OS updates.', 1, NOW(), NOW()),
(3, 'iPad Air 10.9-inch', 'Apple', 'ipad-air-10-9', 'Lightweight tablet for productivity and creativity with Apple Pencil support and powerful chip.', 1, NOW(), NOW()),
(3, 'Kindle Oasis', 'Amazon', 'kindle-oasis', 'Premium e-reader with adjustable warm light, high-resolution e-ink and ergonomic page-turn buttons.', 1, NOW(), NOW()),
(4, 'NVIDIA GeForce RTX 4070 Ti', 'NVIDIA', 'nvidia-geforce-rtx-4070-ti', 'High-performance GPU for 1440p/4K gaming, DLSS support and advanced ray tracing.', 1, NOW(), NOW()),
(4, 'Samsung 980 Pro 2TB NVMe SSD', 'Samsung', 'samsung-980-pro-2tb', 'High-speed NVMe SSD with PCIe 4.0 performance for fast load times and workstation workloads.', 1, NOW(), NOW()),
(4, 'AMD Ryzen 7 7800X3D', 'AMD', 'amd-ryzen-7-7800x3d', 'Gaming-focused CPU featuring 3D V-Cache for improved frame rates in CPU-bound titles.', 1, NOW(), NOW()),
(5, 'Nintendo Switch OLED', 'Nintendo', 'nintendo-switch-oled', 'Portable/home hybrid console with vivid OLED screen and improved kickstand.', 1, NOW(), NOW()),
(5, 'Steam Deck 512GB', 'Valve', 'steam-deck-512gb', 'Handheld gaming PC with high-capacity NVMe storage and configurable settings for PC titles.', 1, NOW(), NOW()),
(6, 'Logitech G502 HERO', 'Logitech', 'logitech-g502-hero', 'Wired gaming mouse with programmable buttons, high-DPI sensor and adjustable weights.', 1, NOW(), NOW()),
(6, 'Keychron K2 Wireless', 'Keychron', 'keychron-k2-wireless', 'Compact mechanical keyboard with Bluetooth multi-device pairing and hot-swappable keys (optional).', 1, NOW(), NOW()),
(7, 'Ubiquiti UniFi 6 Long-Range', 'Ubiquiti', 'ubiquiti-unifi-6-lr', 'Wi-Fi 6 access point designed for extended range and high-density environments.', 1, NOW(), NOW()),
(7, 'TP-Link Archer AX50', 'TP-Link', 'tp-link-archer-ax50', 'Affordable Wi-Fi 6 router with strong coverage and easy setup through mobile app.', 1, NOW(), NOW()),
(8, 'Garmin Forerunner 265', 'Garmin', 'garmin-forerunner-265', 'Advanced running smartwatch with GPS, VO2 max tracking and long battery life.', 1, NOW(), NOW()),
(8, 'Fitbit Inspire 3', 'Fitbit', 'fitbit-inspire-3', 'Slim fitness tracker with heart rate, sleep tracking and simplified notifications.', 1, NOW(), NOW()),
(9, 'Philips Hue Starter Kit (3 bulbs + bridge)', 'Philips', 'philips-hue-starter-kit-3', 'Smart lighting kit with color bulbs, integrated bridge and wide ecosystem compatibility.', 1, NOW(), NOW()),
(10, 'Sennheiser HD 660S2', 'Sennheiser', 'sennheiser-hd-660s2', 'Open-back reference headphones built for audiophiles; balanced soundstage and refined mids.', 1, NOW(), NOW());
